export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Online bank',
    heading: 'Unlimited transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited access',
    heading: 'Login to yyour account at any time, anywhere',
    description: 'We have covered no matter where you are located. All you need is an internet connection and a phone o computer',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/svg-3.svg'),
    alt: 'World',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Join our team',
    heading: 'Creating an account is extremely easy',
    description: 'Get everthing set up and ready in under 10 minutes. All you need to do is add your information and you are ready to go',
    buttonLabel: 'Start now',
    imgStart: false,
    img: require('../../images/svg-2.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}